image: circutor/runner_base:v3

default:
  tags:
    - docker_aws


before_script:
  - echo "List files:" && ls -l
  - echo "User:" && whoami
  - echo "IDs:" && id
  - echo "Hostname:" && hostname
  - echo "Current directory:" && pwd
  - echo "Go version:" && go version

stages:
  - build


build:
  stage: build
  script:
    - make psrecorder
